CREATE TABLE listings (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description LONGTEXT,
    salary VARCHAR(50),
    tags VARCHAR(255),
    company VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(50),
    state VARCHAR(50),
    phone VARCHAR(50),
    email VARCHAR(50),
    requirements LONGTEXT,
    benefits LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY user_id (user_id)
);

INSERT INTO
    listings (
        user_id,
        title,
        description,
        salary,
        tags,
        company,
        address,
        city,
        state,
        phone,
        email,
        requirements,
        benefits
    )
values
    (
        1,
        'Software Engineer',
        'Assists in the design, development, and maintenance of software applications. Works under the guidance of senior engineers to learn and apply coding standards and best practices.',
        '70000',
        'software, engineering, developer',
        'Tech Corp',
        '123 Main St',
        'New York',
        'NY',
        '123-456-7890',
        'jobs@techcorp.com',
        'Experience in Java and SQL.',
        'Health insurance, 401k'
    ),
    (
        2,
        'Data Analyst',
        'Analyzes data to provide insights.',
        '60000',
        'data, analysis, SQL',
        'DataWorks',
        '456 Data St',
        'San Francisco',
        'CA',
        '234-567-8901',
        'jobs@dataworks.com',
        'Experience in data visualization tools.',
        'Health insurance, gym membership'
    ),
    (
        3,
        'Product Manager',
        'Manages product development lifecycle.',
        '90000',
        'product, management, leadership',
        'Innovate Corp',
        '789 Innovation Blvd',
        'Austin',
        'TX',
        '345-678-9012',
        'jobs@innovatecorp.com',
        'Experience in agile methodologies.',
        'Stock options, health insurance'
    ),
    (
        4,
        'Marketing Specialist',
        'Develops marketing campaigns.',
        '50000',
        'marketing, social media, advertising',
        'Advertise Inc',
        '101 Ad St',
        'Los Angeles',
        'CA',
        '456-789-0123',
        'career@advertise.com',
        'Knowledge of SEO and SEM.',
        'Flexible work hours, health insurance'
    ),
    (
        5,
        'Customer Service Representative',
        'Assists customers with inquiries.',
        '30000',
        'customer service, communication, problem solving',
        'ServiceNow',
        '202 Service St',
        'Chicago',
        'IL',
        '567-890-1234',
        'career@servicenow.com',
        'Experience in CRM software.',
        'Paid training, health insurance'
    ),
    (
        6,
        'Graphic Designer',
        'Creates visual concepts to communicate ideas.',
        '55000',
        'design, graphics, creativity',
        'Design Studio',
        '303 Art St',
        'Miami',
        'FL',
        '678-901-2345',
        'jobs@designstudio.com',
        'Proficiency in Adobe Creative Suite.',
        'Flexible working hours, health insurance'
    ),
    (
        7,
        'Sales Manager',
        'Leads the sales team to achieve targets.',
        '80000',
        'sales, management, leadership',
        'SalesForce',
        '404 Sales St',
        'Seattle',
        'WA',
        '789-012-3456',
        'jobs@salesforce.com',
        'Experience in sales strategies.',
        'Commission, health insurance'
    ),
    (
        8,
        'HR Specialist',
        'Manages recruitment and employee relations.',
        '60000',
        'HR, recruitment, employee relations',
        'HR Solutions',
        '505 HR St',
        'Boston',
        'MA',
        '890-123-4567',
        'jobs@hrsolutions.com',
        'Knowledge of labor laws.',
        'Health insurance, retirement plan'
    ),
    (
        9,
        'IT Support Technician',
        'Provides technical support to users.',
        '45000',
        'IT, support, troubleshooting',
        'Tech Support Co',
        '606 Tech St',
        'Denver',
        'CO',
        '901-234-5678',
        'jobs@techsupportco.com',
        'Experience in hardware and software troubleshooting.',
        'Health insurance, paid time off'
    ),
    (
        10,
        'Content Writer',
        'Creates engaging content for various platforms.',
        '40000',
        'writing, content, creativity',
        'Content Creators',
        '707 Write St',
        'Portland',
        'OR',
        '012-345-6789',
        'jobs@contentcreators.com',
        'Excellent writing and editing skills.',
        'Remote work, health insurance'
    );